### ISSUE TITLE
Connect to multiple MYSQL databases

### ISSUE THREAD

**Issue by venca-x** [nette/nette#1053]
Hi, I can not connect to multiple MYSQL databases.

```
nette:                    
    database:             
        default:          
            dsn: 'mysql:host=192.168.1.10;dbname=db1'
            user: root    
            password: xxx 
            options:      
                lazy: true
        db2:              
            dsn: 'mysql:host=192.168.1.10;dbname=db2'
            user: root    
            password: xxx 
            options:      
                lazy: true
services:
    - Db1(@nette.database.default)
    - Db2(@nette.database.db2)  
```

Presenter:

```
/** @var Db1 @inject */
public $db1;

/** @var Db2 @inject */
public $db2;

public function renderDefault()
{
      $this->template->db1 = $this->db1->getAll();
      $this->template->db2 = $this->db2->getAll(); //ERROR
}
```

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db1.table2' doesn't exist

The access to the second database, the data are obtained from the first database
