### ISSUE TITLE
Bug in parsing string starts with at in neon config file

### ISSUE THREAD

**Issue by Sebosek** [nette/nette#1503]
Hello,

I have this configuration in neon

```
parameters:
        LDAP:
                account_suffix: '@sebastian.loc'
                base_dn: 'DC=sebastian,DC=loc'
                domain_controllers: ['192.168.0.109']
```

and Tracy gimme Nette\DI\ServiceCreationException with text: Service ‘90_Model_Orchestration_UserOrchestration’: Reference to missing service ‘sebastian.loc’, but I don't want use service 'sebastian.loc' but string stars with at. I think it's a bug.
