### ISSUE TITLE
nové DI: nastavení $property služby skončí syntax errorem

### ISSUE THREAD

**Issue by janmarek** [nette/nette#405]
```
services:
  application:
    class: Nette\Application\Application
    setup:
      - $errorPresenter(Error)
      - $catchExceptions(%productionMode%)
```

vygeneruje

```
<?php 

class SystemContainer extends Nette\DI\Container
{

public $parameters = array(
    //...
    'common' => array(
        'parameters' => array(
            // ...
        ),
        'services' => array(
            'application' => array(
                'class' => 'Nette\\Application\\Application',
                'setup' => array(
                    (object) array(
                        'value' => '$errorPresenter',
                        'attributes' => array(
                            'Error',
                        ),
                    ),
                    (object) array(
                        'value' => '$catchExceptions',
                        'attributes' => array(
                            '%productionMode%',
                        ),
                    ),
                ),
            ),

// ...
```

přičemž právě to přetypování na objekt PHP poněkud rozhodí.

Nette je stažené z download sekce na webu z večera 10.12.2011.
