### ISSUE TITLE
DI: replacing %foo% in config by parameters does not work for array keys

### ISSUE THREAD

**Issue by janmarek** [nette/nette#766]
I tried to configure authenticator service like this:

```
parameters:
  username: user
  password: 1234

services:
  authenticator: Nette\Security\SimpleAuthenticator({%username%: %password%})
```

And in generated service factory there was 

```
array('%username%' => 1234)
```

passed to constructor.
