### ISSUE TITLE
DIC Factories: automatic resolution of parameters

### ISSUE THREAD

**Issue by fprochazka** [nette/nette#873]
Součástí #839 byl i [tento commit](https://github.com/HosipLan/nette/commit/e5780242cd05f272deb9bfee1e594614dbf22d26), který zajišťoval automatické párování parametrů tovární metody rozhranní a třídy kterou vytváří.

@dg je to podle tebe moc velká magie? Nebo jsi to přehlédl? Je to neskutečně pohodlné.

Srovnej zápis [z příkladu](http://pla.nette.org/cs/inject-dic-factory?rev=13#toc-a-co-formulare)

``` yaml
factories:
    userForm:
        create: App\CreateOrEditUserForm(..., %userId%)
        implement: App\CreateOrEditUserFormFactory
        parameters: [userId]
```

s tím, jak by to mohlo fungovat

``` yaml
factories:
    - App\CreateOrEditUserFormFactory
```

Já bych teda raději přežil trochu magie. Kdyby se tam dodělaly pořádné validace a vysvětlující výjimky, tak by to mohlo velice pěkně fungovat. (I @vrtak-cz byl pro :)
