### ISSUE TITLE
DIC Accessor

### ISSUE THREAD

**Issue by achtan** [nette/nette#875]
Ked uz mame tie skvele [DIC Factories](http://pla.nette.org/cs/inject-dic-factory) tak by bolo fajn spravit aj DIC [Accessors](http://phpfashion.com/di-versus-lazy-loading). 

Fungovalo by to podobne ako Factories:

``` yaml
factories:
    fooAccessor:
        class: Foo
        implement: IFooAccessor
```

Interface by vyzeral tiez poobne:

``` php
interface IFooAccessor
{
    /** @return Foo */
    function get();
}
```

Len by este trebalo v tom neon-e rozlisit ze ide o accessor
