### ISSUE TITLE
"Illegal offset type" when iterating M:N relation using sqlite3

### ISSUE THREAD

**Issue by srigi** [nette/nette#935]
Having supersimple M:N scenario

``` sql
CREATE TABLE "post" (
  "id"    integer  NOT NULL  PRIMARY KEY  AUTOINCREMENT,
  "slug"  text     NOT NULL,
);

CREATE TABLE "tag" (
  "id"    integer  NOT NULL  PRIMARY KEY  AUTOINCREMENT,
  "name"  text     NOT NULL
);

CREATE TABLE "post_tag" (
  "post_id"  integer  NOT NULL,
  "tag_id"   integer  NOT NULL,

  PRIMARY KEY (post_id, tag_id),
  FOREIGN KEY (tag_id) REFERENCES tag(id),
  FOREIGN KEY (post_id) REFERENCES post(id)
);
```

and `config.neon` setup

``` yaml
common:
  nette:
    database:
      default:
        dsn: %database.dsn%
        user: %database.user%
        password: %database.password%

development < common:
  parameters:
    database:
      dsn: sqlite:%appDir%/data/db.sqlite3
      user:
      password:
```

I get PHP Warning "Illegal offset type" when rendering post and iterating through tags 

``` smarty
<p class="tag-links">
  <a n:foreach="$post->related('post_tag') as $post_tag" n:href="tag $post_tag->tag->name">{$post_tag->tag->name}{sep}, {/sep}</a>
</p>
```

You can see red screen [here](http://nette.srigi.sk/issues/sqlite-mn/). Everything is OK if I define `database` service like this:

``` yaml
common:
  services:
    database:
      class: Nette\Database\Connection(%database.dsn%, %database.user%, %database.password%)
```

Or when I use MySql :)

My system conf:
- PHP 5.3.15
- sqlite3 3.7.12 2012-04-03 19:43:07

both are system defaults on Mac OS 10.8.2

I'm getting this error using Nette 2.0.8 or even Nette 2-dev.
